name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # 安装 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
        # 执行 Gradle 构建
      - name: Build with Gradle
        run: ./gradlew build
        # 上传构建产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Subit ForumBackendKtor Artifact
          path: build/libs/*.jar